const NUMBER_OF_MARKERS = 10;
const MIN_TITLE_LENGTH = 30;
const MAX_TITLE_LENGTH = 100;
const MAX_PRICE = 1000000;
const ALERT_SHOW_TIME = 3000;
export {
  NUMBER_OF_MARKERS,
  MIN_TITLE_LENGTH,
  MAX_TITLE_LENGTH,
  MAX_PRICE,
  ALERT_SHOW_TIME
};
